use winit::keyboard::KeyCode;

pub struct Button {
    pub pressed: bool,
    pub just_pressed: bool,
    pub released: bool,
}

impl Button {
    fn new() -> Self {
        Self {
            pressed: false,
            just_pressed: false,
            released: false,
        }
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum KeyboardKey {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
    None,
}

impl KeyboardKey {
    pub fn from(code: KeyCode) -> Self {
        match code {
            KeyCode::Backquote => KeyboardKey::Backquote,
            KeyCode::Backslash => KeyboardKey::Backslash,
            KeyCode::BracketLeft => KeyboardKey::BracketLeft,
            KeyCode::BracketRight => KeyboardKey::BracketRight,
            KeyCode::Comma => KeyboardKey::Comma,
            KeyCode::Digit0 => KeyboardKey::Digit0,
            KeyCode::Digit1 => KeyboardKey::Digit1,
            KeyCode::Digit2 => KeyboardKey::Digit2,
            KeyCode::Digit3 => KeyboardKey::Digit3,
            KeyCode::Digit4 => KeyboardKey::Digit4,
            KeyCode::Digit5 => KeyboardKey::Digit5,
            KeyCode::Digit6 => KeyboardKey::Digit6,
            KeyCode::Digit7 => KeyboardKey::Digit7,
            KeyCode::Digit8 => KeyboardKey::Digit8,
            KeyCode::Digit9 => KeyboardKey::Digit9,
            KeyCode::Equal => KeyboardKey::Equal,
            KeyCode::IntlBackslash => KeyboardKey::IntlBackslash,
            KeyCode::IntlRo => KeyboardKey::IntlRo,
            KeyCode::IntlYen => KeyboardKey::IntlYen,
            KeyCode::KeyA => KeyboardKey::A,
            KeyCode::KeyB => KeyboardKey::B,
            KeyCode::KeyC => KeyboardKey::C,
            KeyCode::KeyD => KeyboardKey::D,
            KeyCode::KeyE => KeyboardKey::E,
            KeyCode::KeyF => KeyboardKey::F,
            KeyCode::KeyG => KeyboardKey::G,
            KeyCode::KeyH => KeyboardKey::H,
            KeyCode::KeyI => KeyboardKey::I,
            KeyCode::KeyJ => KeyboardKey::J,
            KeyCode::KeyK => KeyboardKey::K,
            KeyCode::KeyL => KeyboardKey::L,
            KeyCode::KeyM => KeyboardKey::M,
            KeyCode::KeyN => KeyboardKey::N,
            KeyCode::KeyO => KeyboardKey::O,
            KeyCode::KeyP => KeyboardKey::P,
            KeyCode::KeyQ => KeyboardKey::Q,
            KeyCode::KeyR => KeyboardKey::R,
            KeyCode::KeyS => KeyboardKey::S,
            KeyCode::KeyT => KeyboardKey::T,
            KeyCode::KeyU => KeyboardKey::U,
            KeyCode::KeyV => KeyboardKey::V,
            KeyCode::KeyW => KeyboardKey::W,
            KeyCode::KeyX => KeyboardKey::X,
            KeyCode::KeyY => KeyboardKey::Y,
            KeyCode::KeyZ => KeyboardKey::Z,
            KeyCode::Minus => KeyboardKey::Minus,
            KeyCode::Period => KeyboardKey::Period,
            KeyCode::Quote => KeyboardKey::Quote,
            KeyCode::Semicolon => KeyboardKey::Semicolon,
            KeyCode::Slash => KeyboardKey::Slash,
            KeyCode::AltLeft => KeyboardKey::AltLeft,
            KeyCode::AltRight => KeyboardKey::AltRight,
            KeyCode::Backspace => KeyboardKey::Backspace,
            KeyCode::CapsLock => KeyboardKey::CapsLock,
            KeyCode::ContextMenu => KeyboardKey::ContextMenu,
            KeyCode::ControlLeft => KeyboardKey::ControlLeft,
            KeyCode::ControlRight => KeyboardKey::ControlRight,
            KeyCode::Enter => KeyboardKey::Enter,
            KeyCode::SuperLeft => KeyboardKey::SuperLeft,
            KeyCode::SuperRight => KeyboardKey::SuperRight,
            KeyCode::ShiftLeft => KeyboardKey::ShiftLeft,
            KeyCode::ShiftRight => KeyboardKey::ShiftRight,
            KeyCode::Space => KeyboardKey::Space,
            KeyCode::Tab => KeyboardKey::Tab,
            KeyCode::Convert => KeyboardKey::Convert,
            KeyCode::KanaMode => KeyboardKey::KanaMode,
            KeyCode::Lang1 => KeyboardKey::Lang1,
            KeyCode::Lang2 => KeyboardKey::Lang2,
            KeyCode::Lang3 => KeyboardKey::Lang3,
            KeyCode::Lang4 => KeyboardKey::Lang4,
            KeyCode::Lang5 => KeyboardKey::Lang5,
            KeyCode::NonConvert => KeyboardKey::NonConvert,
            KeyCode::Delete => KeyboardKey::Delete,
            KeyCode::End => KeyboardKey::End,
            KeyCode::Help => KeyboardKey::Help,
            KeyCode::Home => KeyboardKey::Home,
            KeyCode::Insert => KeyboardKey::Insert,
            KeyCode::PageDown => KeyboardKey::PageDown,
            KeyCode::PageUp => KeyboardKey::PageUp,
            KeyCode::ArrowDown => KeyboardKey::ArrowDown,
            KeyCode::ArrowLeft => KeyboardKey::ArrowLeft,
            KeyCode::ArrowRight => KeyboardKey::ArrowRight,
            KeyCode::ArrowUp => KeyboardKey::ArrowUp,
            KeyCode::NumLock => KeyboardKey::NumLock,
            KeyCode::Numpad0 => KeyboardKey::Numpad0,
            KeyCode::Numpad1 => KeyboardKey::Numpad1,
            KeyCode::Numpad2 => KeyboardKey::Numpad2,
            KeyCode::Numpad3 => KeyboardKey::Numpad3,
            KeyCode::Numpad4 => KeyboardKey::Numpad4,
            KeyCode::Numpad5 => KeyboardKey::Numpad5,
            KeyCode::Numpad6 => KeyboardKey::Numpad6,
            KeyCode::Numpad7 => KeyboardKey::Numpad7,
            KeyCode::Numpad8 => KeyboardKey::Numpad8,
            KeyCode::Numpad9 => KeyboardKey::Numpad9,
            KeyCode::NumpadAdd => KeyboardKey::NumpadAdd,
            KeyCode::NumpadBackspace => KeyboardKey::NumpadBackspace,
            KeyCode::NumpadClear => KeyboardKey::NumpadClear,
            KeyCode::NumpadClearEntry => KeyboardKey::NumpadClearEntry,
            KeyCode::NumpadComma => KeyboardKey::NumpadComma,
            KeyCode::NumpadDecimal => KeyboardKey::NumpadDecimal,
            KeyCode::NumpadDivide => KeyboardKey::NumpadDivide,
            KeyCode::NumpadEnter => KeyboardKey::NumpadEnter,
            KeyCode::NumpadEqual => KeyboardKey::NumpadEqual,
            KeyCode::NumpadHash => KeyboardKey::NumpadHash,
            KeyCode::NumpadMemoryAdd => KeyboardKey::NumpadMemoryAdd,
            KeyCode::NumpadMemoryClear => KeyboardKey::NumpadMemoryClear,
            KeyCode::NumpadMemoryRecall => KeyboardKey::NumpadMemoryRecall,
            KeyCode::NumpadMemoryStore => KeyboardKey::NumpadMemoryStore,
            KeyCode::NumpadMemorySubtract => KeyboardKey::NumpadMemorySubtract,
            KeyCode::NumpadMultiply => KeyboardKey::NumpadMultiply,
            KeyCode::NumpadParenLeft => KeyboardKey::NumpadParenLeft,
            KeyCode::NumpadParenRight => KeyboardKey::NumpadParenRight,
            KeyCode::NumpadStar => KeyboardKey::NumpadStar,
            KeyCode::NumpadSubtract => KeyboardKey::NumpadSubtract,
            KeyCode::Escape => KeyboardKey::Escape,
            KeyCode::Fn => KeyboardKey::Fn,
            KeyCode::FnLock => KeyboardKey::FnLock,
            KeyCode::PrintScreen => KeyboardKey::PrintScreen,
            KeyCode::ScrollLock => KeyboardKey::ScrollLock,
            KeyCode::Pause => KeyboardKey::Pause,
            KeyCode::BrowserBack => KeyboardKey::BrowserBack,
            KeyCode::BrowserFavorites => KeyboardKey::BrowserFavorites,
            KeyCode::BrowserForward => KeyboardKey::BrowserForward,
            KeyCode::BrowserHome => KeyboardKey::BrowserHome,
            KeyCode::BrowserRefresh => KeyboardKey::BrowserRefresh,
            KeyCode::BrowserSearch => KeyboardKey::BrowserSearch,
            KeyCode::BrowserStop => KeyboardKey::BrowserStop,
            KeyCode::Eject => KeyboardKey::Eject,
            KeyCode::LaunchApp1 => KeyboardKey::LaunchApp1,
            KeyCode::LaunchApp2 => KeyboardKey::LaunchApp2,
            KeyCode::LaunchMail => KeyboardKey::LaunchMail,
            KeyCode::MediaPlayPause => KeyboardKey::MediaPlayPause,
            KeyCode::MediaSelect => KeyboardKey::MediaSelect,
            KeyCode::MediaStop => KeyboardKey::MediaStop,
            KeyCode::MediaTrackNext => KeyboardKey::MediaTrackNext,
            KeyCode::MediaTrackPrevious => KeyboardKey::MediaTrackPrevious,
            KeyCode::Power => KeyboardKey::Power,
            KeyCode::Sleep => KeyboardKey::Sleep,
            KeyCode::AudioVolumeDown => KeyboardKey::AudioVolumeDown,
            KeyCode::AudioVolumeMute => KeyboardKey::AudioVolumeMute,
            KeyCode::AudioVolumeUp => KeyboardKey::AudioVolumeUp,
            KeyCode::WakeUp => KeyboardKey::WakeUp,
            KeyCode::Meta => KeyboardKey::Meta,
            KeyCode::Hyper => KeyboardKey::Hyper,
            KeyCode::Turbo => KeyboardKey::Turbo,
            KeyCode::Abort => KeyboardKey::Abort,
            KeyCode::Resume => KeyboardKey::Resume,
            KeyCode::Suspend => KeyboardKey::Suspend,
            KeyCode::Again => KeyboardKey::Again,
            KeyCode::Copy => KeyboardKey::Copy,
            KeyCode::Cut => KeyboardKey::Cut,
            KeyCode::Find => KeyboardKey::Find,
            KeyCode::Open => KeyboardKey::Open,
            KeyCode::Paste => KeyboardKey::Paste,
            KeyCode::Props => KeyboardKey::Props,
            KeyCode::Select => KeyboardKey::Select,
            KeyCode::Undo => KeyboardKey::Undo,
            KeyCode::Hiragana => KeyboardKey::Hiragana,
            KeyCode::Katakana => KeyboardKey::Katakana,
            KeyCode::F1 => KeyboardKey::F1,
            KeyCode::F2 => KeyboardKey::F2,
            KeyCode::F3 => KeyboardKey::F3,
            KeyCode::F4 => KeyboardKey::F4,
            KeyCode::F5 => KeyboardKey::F5,
            KeyCode::F6 => KeyboardKey::F6,
            KeyCode::F7 => KeyboardKey::F7,
            KeyCode::F8 => KeyboardKey::F8,
            KeyCode::F9 => KeyboardKey::F9,
            KeyCode::F10 => KeyboardKey::F10,
            KeyCode::F11 => KeyboardKey::F11,
            KeyCode::F12 => KeyboardKey::F12,
            KeyCode::F13 => KeyboardKey::F13,
            KeyCode::F14 => KeyboardKey::F14,
            KeyCode::F15 => KeyboardKey::F15,
            KeyCode::F16 => KeyboardKey::F16,
            KeyCode::F17 => KeyboardKey::F17,
            KeyCode::F18 => KeyboardKey::F18,
            KeyCode::F19 => KeyboardKey::F19,
            KeyCode::F20 => KeyboardKey::F20,
            KeyCode::F21 => KeyboardKey::F21,
            KeyCode::F22 => KeyboardKey::F22,
            KeyCode::F23 => KeyboardKey::F23,
            KeyCode::F24 => KeyboardKey::F24,
            KeyCode::F25 => KeyboardKey::F25,
            KeyCode::F26 => KeyboardKey::F26,
            KeyCode::F27 => KeyboardKey::F27,
            KeyCode::F28 => KeyboardKey::F28,
            KeyCode::F29 => KeyboardKey::F29,
            KeyCode::F30 => KeyboardKey::F30,
            KeyCode::F31 => KeyboardKey::F31,
            KeyCode::F32 => KeyboardKey::F32,
            KeyCode::F33 => KeyboardKey::F33,
            KeyCode::F34 => KeyboardKey::F34,
            KeyCode::F35 => KeyboardKey::F35,
            _ => KeyboardKey::None,
        }
    }
}

#[derive(Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Button4,
    Button5,
    Button6,
    Button7,
    Button8,
    Button9,
    Button10,
    Button11,
    Button12,
    Button13,
    Button14,
    Button15,
    Button16,
    Button17,
    Button18,
    Button19,
    Button20,
    None
}

impl MouseButton {
    pub fn from(button: winit::event::MouseButton) -> Self {
        match button {
            winit::event::MouseButton::Left => MouseButton::Left,
            winit::event::MouseButton::Right => MouseButton::Right,
            winit::event::MouseButton::Middle => MouseButton::Middle,
            winit::event::MouseButton::Back => MouseButton::Button4,
            winit::event::MouseButton::Forward => MouseButton::Button5,
            winit::event::MouseButton::Other(index) => match index {
                5 => MouseButton::Button6,
                6 => MouseButton::Button7,
                7 => MouseButton::Button8,
                8 => MouseButton::Button9,
                9 => MouseButton::Button10,
                10 => MouseButton::Button11,
                11 => MouseButton::Button12,
                12 => MouseButton::Button13,
                13 => MouseButton::Button14,
                14 => MouseButton::Button15,
                15 => MouseButton::Button16,
                16 => MouseButton::Button17,
                17 => MouseButton::Button18,
                18 => MouseButton::Button19,
                19 => MouseButton::Button20,
                _ => MouseButton::None,
            }
        }
    }
}

pub struct Keyboard {
    pub keys: [Button; KeyboardKey::None as usize],
}

impl Keyboard {
    pub fn new() -> Self {
        Self {
            keys: std::array::from_fn(|_| Button::new())
        }
    }
}

pub struct Mouse {
    pub buttons: [Button; MouseButton::None as usize],
}

impl Mouse {
    pub fn new() -> Self {
        Self {
            buttons: std::array::from_fn(|_| Button::new())
        }
    }
}